name: "RuboCop Linter Action"
description: "A GitHub Action that lints your Ruby or Ruby on Rails code with RuboCop!"
inputs:
  action_config_path:
    description: "Define a path to your optional action config file."
    required: false
    default: ".github/config/rubocop_linter_action.yml"
  exit_on_failure:
    description: "Return exit code if linter returns some failures."
    required: false
    default: "true"

env:
  GITHUB_TOKEN: secrets.GITHUB_TOKEN